language: python

python:
  - 3.6

before_install:
  - pip install ablog

script:
  - cd src
  - ablog build

after_success:
  - git config --global user.name "Paul Everitt"
  - git config --global user.email "pauleveritt@me.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`"